name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]   # TÃ¤glich
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Amonoman
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin

          # ðŸ”¥ AktivitÃ¤t
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_visibility: public

          # ðŸŽ¨ Sprachen
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_categories: markup, programming
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5

          # Repositories
          plugin_repositories: yes

          # Stars
          plugin_stars: yes
          plugin_stars_limit: 100

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Code Lines
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4

          # Jokes Card
          plugin_fortune: yes