name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Amonoman
          filename: metrics.svg
          template: classic
          config_timezone: Europe/Berlin

          config_padding: 0
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 3

          config_order: fortune, introduction, activity, languages, stars, achievements

          plugin_introduction: yes
          plugin_introduction_title: "#Moin/Hi Everyone"

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_limit: 5

          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_colors: github

          plugin_stars: yes
          plugin_stars_limit: 0

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_fortune: yes