name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Amonoman
          filename: metrics.svg
          config_timezone: Europe/Berlin

          # Standard-Plugins
          plugin_activity: yes
          plugin_languages: yes
          plugin_followup: no
          plugin_repositories: yes
          plugin_traffic: no
          plugin_achievements: yes
          plugin_stars: yes
          plugin_stars_limit: 100